### ISSUE TITLE
404 for plugin > configure

### ISSUE THREAD

**Issue by Erdou** [pbelikov/redmine-omniauth-oauth-cas#2]
I'm getting a 404 : "The page you were trying to access doesn't exist or has been removed." when I click on "configure" as written in the Install section of the README.

The path is /settings/plugin/redmine_omniauth_isu

So I'm wondering if this has something to do with the renaming of the plugin?

**Comment by pbelikov** [comment]
@Erdou Issue was in naming conventions (repo name and plugin name weren't the same), sorry for that. Just type `mv redmine-omniauth-oauth-cas redmine_omniauth_isu` after cloning and that will do the job. README updated accordingly. d084fa8fb904c665d21aec8f2224ae9717e1960c
