### ISSUE TITLE
Unable to login after installing the plugin

### ISSUE THREAD

**Issue by akhilsikri** [pbelikov/redmine-omniauth-oauth-cas#3]
After installing plugin, it says 404 error for login page. 

The page you were trying to access doesn't exist or has been removed.

https://www.dropbox.com/s/vd9ry2kipelgwc3/Screenshot%202017-07-18%2014.38.05.png?dl=0

**Comment by SimonDahrs** [comment]
From my experience with modifying this plugin, you get this error when your code contains errors. Try to find your error and fix it in order to get the login page working again.

**Comment by caleno** [comment]
Same problem here. 

`Processing by AccountController#login as HTML
  Current user: anonymous
  Rendered account/login.html.erb within layouts/base (4.9ms)
Missing template, responding with 404
`

**Comment by treedbox** [comment]
It happened to me because I skip the step:
`mv redmine-omniauth-oauth-cas redmine_omniauth_isu`
Works fine after rename
