### ISSUE TITLE
not compatible with Redmine 3.4

### ISSUE THREAD

**Issue by jonefeewang** [pbelikov/redmine-omniauth-oauth-cas#4]
very nice plugin. But not compatible with Redmine 3.4， this plugin will not work with it.

**Comment by pbelikov** [comment]
Unfortunately, I dont have any time now to support this plugin. So it wont be updated :(

**Comment by hervehobbes** [comment]
Hello,

This should be highlighted on this page: http://www.redmine.org/plugins/omniauth_oauth2_isu
